import React,{useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
export default function GhostScene({scenario}:{scenario:any}){
 const host=useRef<HTMLDivElement>(null);const [running,setRunning]=useState(true);const run=useRef(true);
 useEffect(()=>{run.current=running},[running]);
 useEffect(()=>{if(!host.current)return;const node=host.current;const scene=new THREE.Scene();scene.background=new THREE.Color('#101b22');const camera=new THREE.PerspectiveCamera(48,1,.1,1000);camera.position.set(13,10,-18);camera.lookAt(0,0,12);
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));node.appendChild(renderer.domElement);scene.add(new THREE.AmbientLight(0xffffff,2));let light=new THREE.DirectionalLight(0xffffff,3);light.position.set(5,15,-5);scene.add(light);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(18,500),new THREE.MeshStandardMaterial({color:0x25333b,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.z=200;scene.add(ground);
 const grid=new THREE.GridHelper(500,100,0x49636e,0x2b414c);grid.position.z=200;grid.position.y=.01;scene.add(grid);
 function car(color:number,ghost:boolean){const g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color,transparent:ghost,opacity:ghost?.42:1,metalness:.3,roughness:.5});function part(geo:THREE.BufferGeometry,x:number,y:number,z:number){let m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);g.add(m);return m}part(new THREE.BoxGeometry(.9,.45,3.6),0,.6,0);part(new THREE.BoxGeometry(1.7,.12,.5),0,.35,1.8);part(new THREE.BoxGeometry(1.7,.16,.55),0,1,-1.7);part(new THREE.SphereGeometry(.4,16,12),0,.95,-.2);for(let x of [-.9,.9])for(let z of [-1.15,1.2]){let wheel=part(new THREE.CylinderGeometry(.38,.38,.34,20),x,.38,z);wheel.rotation.z=Math.PI/2}if(ghost){for(const child of [...g.children]){const mesh=child as THREE.Mesh;const edges=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:0x69e8ff}));edges.position.copy(mesh.position);edges.rotation.copy(mesh.rotation);g.add(edges)}}scene.add(g);return g}
 const rival=car(0x62d9ef,true),ego=car(0x737c89,false);ego.position.x=-2;let last=performance.now(),t=0,raf=0;const resize=()=>{const w=node.clientWidth,h=300;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};resize();const observer=new ResizeObserver(resize);observer.observe(node);
 function render(now:number){if(run.current)t+=(now-last)/1000;last=now;const rows=scenario?.trajectory||[];let row=rows.length?rows[Math.floor(t/.04)%rows.length]:null;rival.position.set(1,0,row?.x||8);ego.position.z=row?.ego_x||0;camera.position.z=rival.position.z-18;camera.lookAt(0,0,rival.position.z+8);renderer.render(scene,camera);raf=requestAnimationFrame(render)}raf=requestAnimationFrame(render);
 return()=>{cancelAnimationFrame(raf);observer.disconnect();scene.traverse(o=>{const m=o as THREE.Mesh;m.geometry?.dispose();if(m.material){const mats=Array.isArray(m.material)?m.material:[m.material];mats.forEach(x=>x.dispose())}});renderer.dispose();node.replaceChildren()}
 },[scenario]);return <div><div ref={host} className="ghost-scene"/><div className="scene-caption"><span>SIMULATED · schematic vehicle geometry</span><button onClick={()=>setRunning(!running)}>{running?'Pause replay':'Play replay'}</button></div></div>
}
