import TrackAlerts from './TrackAlerts';
import {useFrameResults} from './useFrameResults';
import CircuitPanel from './CircuitPanel';
import EvaluationSummary from './EvaluationSummary';
import GhostScene from './GhostScene';
import React,{useEffect,useRef,useState} from 'react';
import {Aperture,Play,Pause,UploadSimple,ChartLine,Stack,FilmStrip,SlidersHorizontal,ArrowSquareOut,ArrowLeft,ArrowRight,DownloadSimple,Flag,Warning,Eye,EyeSlash,Cube,Database,Target,Stop} from '@phosphor-icons/react';
type Asset={id:string;name:string;fps:number;frames:number;width:number;height:number;duration:number;held_out:boolean};
type Job={id:string;asset_id:string;status:string;mode:string;processed:number;total:number;events:number;error?:string;analyzed_frames:number};
const api=async(path:string,body?:any)=>{let r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body instanceof FormData?body:JSON.stringify(body)});if(!r.ok){let e=await r.json();throw Error(e.detail||r.statusText)}return r.json()};
const fmt=(t:number)=>`${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;
export default function Studio(){
 const [state,setState]=useState<any>({assets:[],jobs:[],datasets:{sources:[]},models:[],evaluation:{}}),[page,setPage]=useState('Analysis'),[assetId,setAssetId]=useState(''),[jobId,setJobId]=useState(''),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[overlay,setOverlay]=useState(true),[events,setEvents]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(false),[polygon,setPolygon]=useState<number[][]>([]),[contactText,setContactText]=useState('[]'),[endFrame,setEndFrame]=useState(0),[confidenceText,setConfidenceText]=useState('');
 const [gap,setGap]=useState(8),[speed,setSpeed]=useState(20),[brake,setBrake]=useState(3),[scenario,setScenario]=useState<any>(null),[scenarioMode,setScenarioMode]=useState('parametric');
 const [compute,setCompute]=useState<any>({name:'Checking compute…'});
 const [session,setSession]=useState({year:2024,event:'Monza',session:'Q',driver:'VER'}),[telemetry,setTelemetry]=useState<any>(null),[offset,setOffset]=useState(0);
 const video=useRef<HTMLVideoElement>(null),canvas=useRef<HTMLCanvasElement>(null),upload=useRef<HTMLInputElement>(null);
 const asset:Asset=state.assets.find((a:Asset)=>a.id===assetId)||state.assets[0];const job:Job=state.jobs.find((j:Job)=>j.id===jobId)||state.jobs.find((j:Job)=>j.asset_id===asset?.id);
 const result=useFrameResults(video,job?.id,asset?.fps||25,asset?.frames||1,time,job?.status);
 const refresh=()=>api('state').then(setState).catch(e=>setError(e.message));
 useEffect(()=>{fetch('/api/compute').then(r=>r.json()).then(setCompute);refresh();let t=setInterval(refresh,2500);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(asset){setAssetId(asset.id);setEndFrame(Math.min(asset.frames-1,1750));}},[asset?.id]);
 useEffect(()=>{let active=true;setEvents([]);if(!job)return;const load=()=>api(`jobs/${job.id}/events`).then(e=>{if(active)setEvents(e)}).catch(()=>{});load();const timer=setInterval(load,1500);return()=>{active=false;clearInterval(timer)}},[job?.id]);

 useEffect(()=>{let c=canvas.current;if(!c||!asset)return;let ctx=c.getContext('2d')!;c.width=asset.width;c.height=asset.height;ctx.clearRect(0,0,c.width,c.height);if(!overlay)return;ctx.lineWidth=1.6;ctx.font='12px Arial';
  ctx.lineJoin='round';ctx.lineCap='round';
  for(const car of result.cars||[]){if(!car.mask?.length)continue;ctx.strokeStyle='#84f775';ctx.fillStyle='rgba(132,247,117,.07)';ctx.lineWidth=2.5;ctx.shadowColor='#84f775';ctx.shadowBlur=6;ctx.beginPath();(car.display_mask||car.mask).forEach(([x,y]:number[],i:number)=>i?ctx.lineTo(x*c.width,y*c.height):ctx.moveTo(x*c.width,y*c.height));ctx.closePath();ctx.fill();ctx.stroke();}
  ctx.strokeStyle='#ffffff';ctx.shadowColor='#ffffff';ctx.shadowBlur=14;ctx.lineWidth=Math.max(4,c.width/220);
  for(const line of result.track_lines||[]){ctx.setLineDash(line.kind.startsWith('inferred')?[12,9]:[]);ctx.beginPath();line.points.forEach(([x,y]:number[],i:number)=>i?ctx.lineTo(x*c.width,y*c.height):ctx.moveTo(x*c.width,y*c.height));ctx.stroke();}ctx.setLineDash([]);ctx.shadowBlur=0;
  let p:number[][]=polygon.length?polygon:result.track_polygon||[];if(p.length){ctx.strokeStyle='#ffffff';ctx.beginPath();p.forEach(([x,y],i)=>i?ctx.lineTo(x*c.width,y*c.height):ctx.moveTo(x*c.width,y*c.height));ctx.closePath();ctx.stroke();}
 },[result,overlay,polygon,asset,page]);
 async function action(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function seek(t:number){if(!asset)return;const next=Math.max(0,Math.min(t,asset.duration));setTime(next);if(video.current)video.current.currentTime=next}
 async function run(mode:string){await action(async()=>{let c=JSON.parse(contactText);if(c.length&&c.length!==4)throw Error('Supply exactly four contact polygons');let j=await api('jobs',{asset_id:asset.id,mode,calibration:polygon.length?{polygon,contacts:c,start_frame:Math.round(time*asset.fps),end_frame:endFrame,...(confidenceText!==''?{confidence:Number(confidenceText)}:{})}: {}});setJobId(j.id)})}
 const nav=[['Analysis',FilmStrip],['Datasets',Database],['Models',ChartLine],['Alignment',Target],['Scenarios',Cube],['Exports',DownloadSimple]] as const;
 return <div className="shell"><aside className="rail"><div className="brand"><Aperture size={31} weight="duotone"/><span>GHOST<span className="brand-sub">RIVAL STUDIO</span></span></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(([label,Icon])=><button className={page===label?'nav active':'nav'} key={label} onClick={()=>setPage(label)}><Icon size={21}/>{label}</button>)}</nav><div className="rail-bottom"><span className="local-dot"/> Local workspace<p>Recorded footage research</p><small>Every estimate retains its evidence.</small></div></aside>
 <main><header><div><span className="eyebrow">GHOST RIVAL / {page.toUpperCase()}</span><h1>{page==='Analysis'?'On-track intelligence':page}</h1></div><div className="header-actions"><span className="pill">LOCAL PROCESSING</span><button className="primary" onClick={()=>upload.current?.click()}><UploadSimple size={18}/> Import video</button><input ref={upload} type="file" accept="video/*" hidden onChange={e=>{if(e.target.files?.[0])action(async()=>{const f=new FormData();f.append('file',e.target.files![0]);let a=await api('assets',f);setAssetId(a.id)})}}/></div></header>
 {error&&<div className="error" role="alert"><Warning/> {error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {page==='Analysis'&&<><div className="project-bar"><div><span className="project-icon"><FilmStrip size={23}/></span><div><strong>{asset?.name||'Import footage to begin'}</strong><p>{asset?`${asset.width} × ${asset.height} · ${asset.fps} FPS · ${fmt(asset.duration)} · ${asset.held_out?'Reserved test footage':'Imported source'}`:'MP4 and other supported formats'}</p></div></div><select aria-label="Selected video" value={asset?.id||''} onChange={e=>{setAssetId(e.target.value);setJobId('');setPolygon([]);seek(0)}}>{state.assets.map((a:Asset)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>
 <div className="analysis-grid"><section className="viewer-card"><div className="panel-title"><span>Source viewer <span className="muted">/ cockpit & external cameras</span></span><button className="subtle" onClick={()=>setOverlay(!overlay)}>{overlay?<Eye size={17}/>:<EyeSlash size={17}/>} {overlay?'Overlays on':'Original'}</button></div><div className="video-wrap">{asset&&<video ref={video} key={asset.id} src={`/api/assets/${asset.id}/video`} poster={`/api/assets/${asset.id}/poster`} onLoadedMetadata={()=>seek(time)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)}/>}<canvas ref={canvas} onClick={e=>{if(edit){const r=e.currentTarget.getBoundingClientRect();setPolygon([...polygon,[(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]])}}} className={edit?'editing':''}/><div className="video-label">{edit?'CLICK TRACK POLYGON VERTICES':'SOURCE FOOTAGE'}<span>{job?`${job.mode.toUpperCase()} · ${job.status}`:'READY TO ANALYZE'}</span></div><div className="legend"><span className="green">Car contours</span><span>White · observed candidates</span><span>Dashed · inferred</span></div></div>
 <div className="transport"><button aria-label="Previous frame" onClick={()=>seek(time-1/asset.fps)}><ArrowLeft size={17}/></button><button aria-label={playing?'Pause':'Play'} className="play" onClick={()=>playing?video.current?.pause():video.current?.play()}>{playing?<Pause weight="fill"/>:<Play weight="fill"/>}</button><button aria-label="Next frame" onClick={()=>seek(time+1/asset.fps)}><ArrowRight size={17}/></button><strong>{fmt(time)}</strong><input aria-label="Video timeline" type="range" min="0" max={asset?.duration||1} step={1/(asset?.fps||25)} value={time} onChange={e=>seek(+e.target.value)}/><span>{fmt(asset?.duration||0)}</span><select aria-label="Playback speed" onChange={e=>{if(video.current)video.current.playbackRate=+e.target.value}} defaultValue="1"><option value=".25">0.25×</option><option value=".5">0.5×</option><option value="1">1×</option><option value="2">2×</option></select></div>
 <div className="viewer-foot"><span>Frame {Math.round(time*(asset?.fps||25)).toLocaleString()} <span className="muted">/ {asset?.frames.toLocaleString()}</span></span><span className="muted">Original perspective preserved · {result.schema_version<3?'Legacy run · reprocess for contours':'Segmentation overlays'}</span></div></section>
 <aside className="inspector"><TrackAlerts key={job?.id||asset?.id} events={events} result={result} onSeek={seek}/><div className="compute-status">{compute.name} · {compute.gpu_available?'CUDA accelerated':'CPU fallback'}</div><div className="panel-title">Analysis controls <SlidersHorizontal size={18}/></div><label>ANALYSIS RUN<select aria-label="Selected analysis" value={job?.id||''} onChange={e=>setJobId(e.target.value)}>{state.jobs.filter((j:Job)=>j.asset_id===asset?.id).map((j:Job)=><option value={j.id} key={j.id}>{j.mode} · {j.status} · {j.analyzed_frames||0} frames</option>)}</select></label><label>PROCESSING MODE</label><button className="primary wide" disabled={busy||!asset} onClick={()=>run('final')}><Play size={17}/> Analyze every frame</button><button className="secondary wide" disabled={busy||!asset} onClick={()=>run('preview')}>Quick preview · 1 FPS / first minute</button>{job&&<div className="job-progress"><div><strong>{job.status==='queued'?'Queued - starts automatically':job.status}</strong><span>{Math.round(100*job.processed/Math.max(1,job.total))}%</span></div><progress max={job.total} value={job.processed}/><p>{job.processed.toLocaleString()} frames decoded</p>{['running','queued'].includes(job.status)?<button onClick={()=>action(()=>api(`jobs/${job.id}/cancel`,{}))}><Stop size={14}/> Cancel</button>:['cancelled','interrupted','failed','incomplete'].includes(job.status)&&<button onClick={()=>action(()=>api(`jobs/${job.id}/resume`,{}))}>Restart consistently</button>}{job.error&&<p className="amber">{job.error}</p>}</div>}
 <div className="divider"/><label>TRACK-LIMIT ESTIMATE</label><h3>{result.track_limit||'Awaiting analysis'}</h3><p className="explain">{result.evidence||'Run analysis to inspect visible cars, painted-line candidates and camera motion.'}</p><div className="confidence"><span>Confidence</span><strong>{result.confidence==null?'Unavailable':`${Math.round(result.confidence*100)}%`}</strong></div><small>Uncalibrated · not an officiating decision</small><div className="divider"/><button className="secondary wide" onClick={()=>setEdit(!edit)}><Target size={17}/>{edit?'Finish polygon':'Review track geometry'}</button>{edit&&<div className="geometry"><p>Click the permitted track polygon. Apply only to frames where this geometry remains valid.</p><button onClick={()=>setPolygon([])}>Clear polygon</button><label>Optional analyst confidence (0â€“1; uncalibrated)<input type="number" min="0" max="1" step="0.05" value={confidenceText} onChange={e=>setConfidenceText(e.target.value)}/></label><label>Last applicable frame<input type="number" value={endFrame} onChange={e=>setEndFrame(+e.target.value)}/></label><label>Four contact polygons (normalized JSON)<textarea value={contactText} onChange={e=>setContactText(e.target.value)}/></label><button onClick={()=>action(()=>api('annotations',{asset_id:asset.id,frame:Math.round(time*asset.fps),end_frame:endFrame,polygon,contacts:JSON.parse(contactText),provenance:'analyst supplied'}))}>Save annotation</button></div>}<CircuitPanel assetId={asset?.id} videoTime={time} onSelectAsset={id=>{setAssetId(id);setJobId('');setTime(0)}}/></aside></div>
 <div className="lower-grid"><section className="panel"><div className="panel-title">Event review <span className="badge">{events.length}</span></div>{events.length?events.map((ev,i)=><button className="event" key={i} onClick={()=>seek(ev.time)}><Flag className="amber"/><strong>{fmt(ev.time)}</strong><span>{ev.type}</span><small>{ev.confidence==null?'Score unavailable':Math.round(ev.confidence*100)+'%'} · uncalibrated</small></button>):<div className="empty"><Flag size={27}/><div><strong>{job?'No supported flags recorded':'Your event timeline starts here'}</strong><p>{job?'Missing geometry is not proof that the car stayed inside.':'Single-frame suspected excursions remain visible.'}</p></div></div>}</section><section className="panel"><div className="panel-title">Tracked vehicles <span className="badge">{result.cars?.length||0}</span></div>{result.cars?.length?result.cars.map((c:any)=><div className="car-row" key={c.id}><span className="green">{c.identity_status==='F1 identity unverified'?'CANDIDATE':'CAR'} {c.id}</span><span>{c.motion}<small>{c.identity_status==='F1 identity unverified'&&<>F1 identity unverified<br/></>}{c.speed_change}<br/>{c.heading_degrees==null?'Heading unavailable':`${c.heading_degrees.toFixed(1)}° image-motion heading`}</small></span><span>{Math.round(c.score*100)}%</span></div>):<div className="empty"><Eye size={27}/><div><strong>No external car detections in this frame</strong><p>An onboard ego car may not form a complete detectable box.</p></div></div>}</section></div></>}
 {page==='Datasets'&&<><div className="summary-strip"><div><strong>{state.datasets.sources?.filter((s:any)=>s.status.includes('acquired')).length||0}</strong><span>Acquired sources</span></div><div><strong>{((state.datasets.used_bytes||0)/1e9).toFixed(2)} GB</strong><span>Of 50 GB dataset budget</span></div><div><strong>Held out</strong><span>Your original test video</span></div></div><section className="panel"><div className="panel-title">Source inventory <span className="muted">Evidence & access status</span></div><div className="table-scroll"><table><thead><tr><th>Source</th><th>Data</th><th>Labels</th><th>Status</th><th>Notes</th></tr></thead><tbody>{state.datasets.sources?.map((s:any)=><tr key={s.id}><td><a href={s.url} target="_blank" rel="noreferrer">{s.id} <ArrowSquareOut/></a><small>{s.license}</small></td><td>{s.kind}</td><td>{s.labels.join(', ')}</td><td><span className="pill">{s.status}</span></td><td>{s.reason||'Source downloaded'}</td></tr>)}</tbody></table></div></section></>}
 {page==='Models'&&<><div className="summary-strip"><div><strong>{state.models.filter((m:string)=>m!=='yolo11n.pt').length}</strong><span>Trained checkpoints</span></div><div><strong>{compute.gpu_available?'CUDA':'CPU'}</strong><span>{compute.name}</span></div><div><strong>Uncalibrated</strong><span>Event confidence</span></div></div><section className="panel"><div className="panel-title">Training & evaluation</div><p className="explain">Checkpoints record training, not proof of broad accuracy. Evaluation must separate cameras and source recordings.</p>{state.models.map((m:string)=><div className="model-row" key={m}><Stack size={24}/><strong>{m}</strong><span className="pill">{m==='yolo11n.pt'?'PRETRAINED BASELINE':'TRAINED CHECKPOINT'}</span></div>)}<EvaluationSummary evaluation={state.evaluation}/><details><summary>Inspect full evaluation evidence</summary><pre>{JSON.stringify(state.evaluation,null,2)}</pre></details></section></>}
 {page==='Alignment'&&<div className="two-col"><section className="panel form-panel"><div className="panel-title">Match a recorded session</div>{Object.entries(session).map(([k,v])=><label key={k}>{k.toUpperCase()}<input value={v} onChange={e=>setSession({...session,[k]:k==='year'?+e.target.value:e.target.value})}/></label>)}<button className="primary" disabled={busy} onClick={()=>action(async()=>setTelemetry(await api('telemetry',session)))}>{busy?'Loading session…':'Load FastF1 telemetry'}</button><p className="explain">Only match footage whose session identity you know. External channels remain separate from video estimates.</p></section><section className="panel form-panel"><div className="panel-title">Synchronization review</div><label>Video offset (seconds)<input type="number" value={offset} onChange={e=>setOffset(+e.target.value)}/></label><button className="secondary" onClick={()=>action(()=>api('annotations',{asset_id:asset?.id,telemetry_id:telemetry?.id,offset_seconds:offset,status:'manual timing anchor; spatial alignment unverified'}))}>Save timing anchor</button>{telemetry?<><p>{telemetry.rows?.length} samples loaded</p><pre>{JSON.stringify({...telemetry,rows:telemetry.rows?.slice(0,3)},null,2)}</pre></>:<div className="empty">No matched telemetry</div>}</section></div>}
 {page==='Scenarios'&&<div className="two-col"><section className="panel form-panel"><div className="panel-title">Hypothetical rival</div><label>MODE<select value={scenarioMode} onChange={e=>setScenarioMode(e.target.value)}><option value="parametric">Parameterized ghost</option><option value="responsive">Separate responsive reconstruction</option></select></label>{[['Initial gap (m)',gap,setGap],['Assumed speed (m/s)',speed,setSpeed],['Braking onset (s)',brake,setBrake]].map(([l,v,fn]:any)=><label key={l}>{l}<input type="number" value={v} onChange={e=>fn(+e.target.value)}/></label>)}<button className="primary" onClick={()=>action(async()=>setScenario(await api('scenarios',{mode:scenarioMode,gap,speed,braking:brake})))}>Simulate trajectory</button><p className="explain">A simplified one-dimensional motion experiment. The recorded driver does not react to this rival.</p><span className="pill">CARLA: {state.carla?.status||'pending'}</span></section><section className="panel"><div className="panel-title">Scenario results <span className="cyan">SIMULATED</span></div>{scenario?<><GhostScene scenario={scenario}/><p className="explain">{scenario.model}</p><div className="trajectory">{scenario.trajectory.filter((_:any,i:number)=>i%10===0).map((p:any)=><div key={p.time} style={{height:`${Math.max(3,p.speed/120*100)}%`}} title={`${p.time}s · ${p.speed.toFixed(1)} m/s`}/>)}</div><p className="explain">Assumed speed over 10 seconds · {scenario.trajectory.length} steps</p><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(scenario,null,2)],{type:'application/json'}));a.download='scenario.json';a.click();URL.revokeObjectURL(a.href)}}>Download scenario</button></>:<div className="empty">Set assumptions and run a scenario.</div>}</section></div>}
 {page==='Exports'&&<section className="panel"><div className="panel-title">Evidence packages</div><p className="explain">Exports retain source identity, versions, limitations and recorded-versus-simulated labels.</p>{state.jobs.filter((j:Job)=>['complete','cancelled','incomplete'].includes(j.status)).map((j:Job)=><div className="export-row" key={j.id}><div><strong>{state.assets.find((a:Asset)=>a.id===j.asset_id)?.name}</strong><p>{j.mode} · {j.status} · {j.analyzed_frames||0} analyzed frames</p></div>{['video','still','csv','json','manifest'].map(k=><a className="secondary" href={`/api/jobs/${j.id}/export/${k}`} key={k}><DownloadSimple/>{k}</a>)}</div>)}</section>}
 <footer><span>Observed / Estimated / Simulated</span><span>Research workspace · no official affiliation</span></footer></main></div>
}





